"""Sub-LLM that turns raw LiDAR sector data into a natural-language summary.

The main flow_3 agent receives a map image plus an *interpreted* LiDAR
description (instead of the raw 6-sector table). The interpretation is
generated by a small/cheap LLM whose only job is to translate sector
distances into a 2-3 sentence safety read, front-first.

Why a separate LLM?

- The main agent has to reason about routing, map vs LiDAR reconciliation,
  and the next move all at once. Pre-digesting the LiDAR keeps the main
  agent's prompt short and lets us emphasize "what is in front" without
  adding more rules.
- Using a smaller / faster model for the interpreter (Claude Haiku by
  default) keeps the cost and rate-limit footprint modest even when the
  main agent runs Sonnet 4.6 or similar.

Configuration (env vars):

- ``FLOW3_INTERPRETER_LLM_PROVIDER``: defaults to ``FLOW3_LLM_PROVIDER``
  (which itself defaults to ``LLM_PROVIDER``).
- ``FLOW3_INTERPRETER_LLM_MODEL``: defaults to ``claude-haiku-4-5``.

The interpreter is created lazily on first use and cached at module
level. If the LLM call fails for any reason we fall back to the raw
sector text so the main agent still has data to work with.
"""

from __future__ import annotations

import os
from typing import Any

from langchain.chat_models import init_chat_model
from langchain_core.messages import HumanMessage, SystemMessage


_INTERPRETER_SYSTEM_PROMPT = """\
You are a navigation safety analyst for a small TurtleBot3 (~0.15 m radius).
You receive a 6-sector LiDAR snapshot in the format:

  - <sector_name>: <distance_m> <STATUS>

Sectors are: front, front_left, back_left, back, back_right, front_right
(compass-style around the robot, "front" = where the robot is currently
facing). Status labels: BLOCKED (< 0.40 m), CAUTION (< 1.00 m), CLEAR.

Your job: produce a 2-4 sentence plain-English read of the situation
that another LLM will use together with a top-down map to pick the next
move. Follow this structure exactly:

1. FIRST sentence: what is in FRONT. This is the most important sector.
   State the distance and status. If BLOCKED, call it out as "do NOT
   move forward". If CLEAR, say roughly how much room is ahead.
2. SECOND sentence: any OTHER sectors that are BLOCKED, named explicitly.
   If none, say so ("All other sectors are clear or only mildly close.").
3. THIRD sentence (optional): a one-line recommendation for what to do
   next, biased toward forward motion when safe and toward rotating
   toward the most-CLEAR sector when blocked.
4. Optional FOURTH sentence: a brief note on side caution if any sector
   under 0.50 m exists that wasn't already flagged.

Rules:
- Be terse. No fluff, no apologies, no preamble.
- Never recommend turning away from the goal unless the front is
  unsafe; you do not know where the goal is, so just optimize for
  immediate physical safety with a forward bias.
- Never invent values; only use what is in the input.
"""


_interpreter_llm: Any | None = None


def _resolve_interpreter_config() -> tuple[str, str]:
    provider = (
        os.environ.get("FLOW3_INTERPRETER_LLM_PROVIDER", "").strip()
        or os.environ.get("FLOW3_LLM_PROVIDER", "").strip()
        or os.environ.get("LLM_PROVIDER", "").strip()
        or "anthropic"
    )
    model = (
        os.environ.get("FLOW3_INTERPRETER_LLM_MODEL", "").strip()
        or "claude-haiku-4-5"
    )
    return provider, model


def _get_interpreter() -> Any:
    global _interpreter_llm
    if _interpreter_llm is None:
        provider, model = _resolve_interpreter_config()
        _interpreter_llm = init_chat_model(
            model=model,
            model_provider=provider,
            temperature=0.0,
        )
    return _interpreter_llm


def interpret_lidar(sector_text: str) -> str:
    """Translate ``sector_text`` (output of ``summarize_scan``) into a
    short natural-language safety read. Falls back to the raw sector
    text if the sub-LLM call fails for any reason.
    """
    if not sector_text:
        return "LiDAR not available."
    try:
        llm = _get_interpreter()
        messages = [
            SystemMessage(content=_INTERPRETER_SYSTEM_PROMPT),
            HumanMessage(content=sector_text),
        ]
        resp = llm.invoke(messages)
        text = getattr(resp, "content", "")
        if isinstance(text, list):
            text = " ".join(
                p.get("text", "") for p in text
                if isinstance(p, dict) and p.get("type") == "text"
            ).strip()
        text = (text or "").strip()
        if not text:
            raise RuntimeError("interpreter returned empty content")
        return text
    except Exception as exc:  # noqa: BLE001 - fall back to raw text
        return (
            "LiDAR interpreter unavailable "
            f"({type(exc).__name__}: {exc}). Raw sector data:\n"
            f"{sector_text}"
        )


__all__ = ["interpret_lidar"]
