"""map_server + RViz + click coordinate echo for marking start/destination poses.

Two launch flows, picked automatically based on the ``world`` argument:

A) world_to_map flow (preferred — pass ``world:=…``):
   - Delegates Gazebo / robot spawn / map_server / lifecycle_manager /
     static map→odom TF / RViz (focused on robot) to
     ``world_to_map.launch.py``.
   - Adds the ``click_echo`` node on top so RViz "Publish Point" clicks
     print both ``MAP`` and ``GAZEBO WORLD`` coordinates.
   - This guarantees the Gazebo scene matches the rasterized PGM, with
     the robot at the same place in both views.

B) Hand-crafted PGM flow (no ``world`` arg):
   - Optionally launches the default TurtleBot3 world (``launch_gazebo``
     defaults to ``true``) for visual reference only.
   - Brings up its own ``map_server`` + lifecycle + static TF + RViz +
     ``click_echo`` against the supplied ``map_yaml``.
   - Use this for legacy maps that have no ``.world_map.yaml`` sidecar.

``map_offset_x`` / ``map_offset_y`` must equal the ``world_to_map_offset``
from the sidecar (the runner script reads it for you).  They are applied
as the static ``map → odom`` translation so:

   map_coords  =  gazebo_world_coords  +  (map_offset_x, map_offset_y)

For maps generated by ``world_to_map`` use the runner script which reads
the sidecar automatically:

   bash src/custom_map_builder/scripts/run_map_builder.sh warehouse
"""

from __future__ import annotations

import os
from typing import List

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription, OpaqueFunction
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def _launch_setup(context, *_args, **_kwargs) -> List:
    use_sim_time = LaunchConfiguration('use_sim_time').perform(context).lower() == 'true'
    map_yaml_arg = LaunchConfiguration('map_yaml').perform(context).strip()
    launch_gazebo = LaunchConfiguration('launch_gazebo').perform(context).lower() == 'true'
    launch_rviz = LaunchConfiguration('launch_rviz').perform(context).lower() == 'true'
    map_offset_x = LaunchConfiguration('map_offset_x').perform(context).strip()
    map_offset_y = LaunchConfiguration('map_offset_y').perform(context).strip()
    world_arg = LaunchConfiguration('world').perform(context).strip()
    gazebo_model_path = LaunchConfiguration('gazebo_model_path').perform(context).strip()
    x_pose = LaunchConfiguration('x_pose').perform(context).strip()
    y_pose = LaunchConfiguration('y_pose').perform(context).strip()
    z_pose = LaunchConfiguration('z_pose').perform(context).strip()
    yaw = LaunchConfiguration('yaw').perform(context).strip()

    pkg_share = get_package_share_directory('custom_map_builder')
    if not map_yaml_arg:
        map_yaml = os.path.join(pkg_share, 'maps', 'default.yaml')
    elif os.path.isabs(map_yaml_arg):
        map_yaml = map_yaml_arg
    else:
        map_yaml = os.path.join(pkg_share, 'maps', map_yaml_arg)
    map_yaml = os.path.abspath(map_yaml)
    if not os.path.isfile(map_yaml):
        raise FileNotFoundError(f'map yaml not found: {map_yaml}')

    actions: List = []

    click_echo = Node(
        package='custom_map_builder',
        executable='click_echo',
        name='map_click_echo',
        output='screen',
        parameters=[
            {'use_sim_time': use_sim_time},
            {'map_offset_x': float(map_offset_x or '0.0')},
            {'map_offset_y': float(map_offset_y or '0.0')},
        ],
    )

    if world_arg:
        # ── Path A: world_to_map flow ────────────────────────────────────
        # Delegate Gazebo + spawn + map_server + lifecycle + static TF +
        # RViz to world_to_map.launch.py, which already does all of that
        # exactly the same way nav2_llm_demo does.  Only add click_echo
        # on top.
        if not os.path.isfile(world_arg):
            raise FileNotFoundError(f'world file not found: {world_arg}')

        world_to_map_share = get_package_share_directory('world_to_map')
        actions.append(IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(
                    world_to_map_share, 'launch', 'world_to_map.launch.py'
                )
            ),
            launch_arguments={
                'world': world_arg,
                'map_yaml': map_yaml,
                'x_pose': x_pose or '0.0',
                'y_pose': y_pose or '0.0',
                'z_pose': z_pose or '0.05',
                'yaw': yaw or '0.0',
                'map_offset_x': map_offset_x or '0.0',
                'map_offset_y': map_offset_y or '0.0',
                'launch_rviz': 'true' if launch_rviz else 'false',
                'use_sim_time': 'true' if use_sim_time else 'false',
                'gazebo_model_path': gazebo_model_path,
            }.items(),
        ))
        actions.append(click_echo)
        return actions

    # ── Path B: hand-crafted PGM flow (no .world file) ─────────────────
    if launch_gazebo:
        actions.append(
            IncludeLaunchDescription(
                PythonLaunchDescriptionSource(
                    [
                        PathJoinSubstitution(
                            [
                                FindPackageShare('turtlebot3_gazebo'),
                                'launch',
                                'turtlebot3_world.launch.py',
                            ]
                        )
                    ]
                ),
                launch_arguments={
                    'use_sim_time': LaunchConfiguration('use_sim_time'),
                    'use_rviz': 'false',
                }.items(),
            )
        )

    rviz_cfg = os.path.join(pkg_share, 'rviz', 'map_builder.rviz')

    actions.extend(
        [
            Node(
                package='nav2_map_server',
                executable='map_server',
                name='map_server',
                output='screen',
                parameters=[
                    {'use_sim_time': use_sim_time},
                    {'yaml_filename': map_yaml},
                ],
            ),
            Node(
                package='nav2_lifecycle_manager',
                executable='lifecycle_manager',
                name='lifecycle_manager',
                output='screen',
                parameters=[
                    {'use_sim_time': use_sim_time},
                    {'autostart': True},
                    {'node_names': ['map_server']},
                    {'bond_timeout': 20.0},
                ],
            ),
            Node(
                package='tf2_ros',
                executable='static_transform_publisher',
                name='static_map_to_odom',
                arguments=[
                    '--x', map_offset_x or '0.0',
                    '--y', map_offset_y or '0.0',
                    '--z', '0',
                    '--qx', '0',
                    '--qy', '0',
                    '--qz', '0',
                    '--qw', '1',
                    '--frame-id', 'map',
                    '--child-frame-id', 'odom',
                ],
                parameters=[{'use_sim_time': use_sim_time}],
            ),
            click_echo,
        ]
    )

    if launch_rviz:
        actions.append(
            Node(
                package='rviz2',
                executable='rviz2',
                name='rviz2',
                arguments=['-d', rviz_cfg],
                parameters=[{'use_sim_time': use_sim_time}],
                output='screen',
            )
        )

    return actions


def generate_launch_description() -> LaunchDescription:
    return LaunchDescription(
        [
            DeclareLaunchArgument(
                'use_sim_time',
                default_value='true',
                description='Must be true when Gazebo is the clock source.',
            ),
            DeclareLaunchArgument(
                'map_yaml',
                default_value='',
                description=(
                    'Empty = share/custom_map_builder/maps/default.yaml. '
                    'Otherwise absolute path to map YAML, or a filename under maps/.'
                ),
            ),
            DeclareLaunchArgument(
                'world',
                default_value='',
                description=(
                    'Absolute path to a Gazebo .world file. When set, the '
                    'launch delegates to world_to_map.launch.py so Gazebo '
                    'shows the SAME world the PGM was rasterized from.  '
                    'Leave empty for hand-crafted PGM maps.'
                ),
            ),
            DeclareLaunchArgument(
                'gazebo_model_path',
                default_value='',
                description=(
                    'Colon-separated extra dirs to prepend to '
                    'GAZEBO_MODEL_PATH so Gazebo can resolve <include> '
                    '<uri>model://…</uri> tags in the .world file.'
                ),
            ),
            DeclareLaunchArgument(
                'x_pose',
                default_value='0.0',
                description='Robot spawn x (Gazebo world frame, world_to_map flow only).',
            ),
            DeclareLaunchArgument(
                'y_pose',
                default_value='0.0',
                description='Robot spawn y (Gazebo world frame, world_to_map flow only).',
            ),
            DeclareLaunchArgument('z_pose', default_value='0.05'),
            DeclareLaunchArgument('yaw', default_value='0.0'),
            DeclareLaunchArgument(
                'map_offset_x',
                default_value='0.0',
                description=(
                    'Translation of the map->odom static TF along X (meters). '
                    'Must match world_to_map_offset[0] in the .world_map.yaml sidecar '
                    'so that map-frame coordinates align 1:1 with Gazebo world coordinates. '
                    'Default 0.0 keeps the old behaviour for hand-crafted PGM maps.'
                ),
            ),
            DeclareLaunchArgument(
                'map_offset_y',
                default_value='0.0',
                description=(
                    'Translation of the map->odom static TF along Y (meters). '
                    'Must match world_to_map_offset[1] in the .world_map.yaml sidecar.'
                ),
            ),
            DeclareLaunchArgument(
                'launch_gazebo',
                default_value='true',
                description=(
                    'Hand-crafted-map flow only.  Set false to skip the '
                    'default turtlebot3_world Gazebo bringup.  Ignored when '
                    'world:= is provided (world_to_map.launch.py always '
                    'starts Gazebo).'
                ),
            ),
            DeclareLaunchArgument(
                'launch_rviz',
                default_value='true',
                description='Set false for headless (coordinates only via echo if another RViz publishes).',
            ),
            OpaqueFunction(function=_launch_setup),
        ]
    )
