"""Subscribe to RViz Publish Point (/clicked_point) and log coordinates.

Prints both the **map-frame** coordinate (what RViz reports) and the
**Gazebo world-frame** coordinate:

  world_x = map_x - map_offset_x
  world_y = map_y - map_offset_y

``map_offset_x`` / ``map_offset_y`` are ROS parameters that must equal the
``world_to_map_offset`` values in the ``.world_map.yaml`` sidecar generated by
``world_to_map``.  The ``map_builder.launch.py`` passes them automatically when
you use ``run_map_builder.sh``.  For old hand-crafted maps both default to 0 so
the behaviour is unchanged.
"""

from __future__ import annotations

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import PointStamped


class MapClickEcho(Node):
    """Print map-frame and Gazebo world-frame coordinates for each clicked point."""

    def __init__(self) -> None:
        super().__init__('map_click_echo')
        self.declare_parameter('map_offset_x', 0.0)
        self.declare_parameter('map_offset_y', 0.0)
        self._offset_x: float = self.get_parameter('map_offset_x').value
        self._offset_y: float = self.get_parameter('map_offset_y').value
        self._sub = self.create_subscription(
            PointStamped,
            '/clicked_point',
            self._on_point,
            10,
        )
        self.get_logger().info(
            f'Listening on /clicked_point  '
            f'(map_offset=({self._offset_x:.4f}, {self._offset_y:.4f}) → '
            f'world = map − offset). '
            f'In RViz use the "Publish Point" tool and click on the map.'
        )

    def _on_point(self, msg: PointStamped) -> None:
        f = msg.header.frame_id
        mx, my = msg.point.x, msg.point.y
        wx = mx - self._offset_x
        wy = my - self._offset_y
        self.get_logger().info(
            f'frame="{f}"  '
            f'MAP  x={mx:.4f}  y={my:.4f}  |  '
            f'GAZEBO WORLD  x={wx:.4f}  y={wy:.4f}'
        )


def main() -> None:
    rclpy.init()
    node = MapClickEcho()
    try:
        rclpy.spin(node)
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
